### PR TITLE
Changing jquery dependency versions

### PR DESCRIPTION
**Pull request by eliotik**

### CODE REVIEW

**Comment by helios-ag** [comment]
@eliotik Imagine situation if you have other dependencies, that require jquery for example ~1.9, with resctricting it to minimum of 1.11 here, the dependency resolver will stuck. Thats why i think it's better to set ~1.8, and you can manually add jquery lib with your own version, and everyone will be happy! :-)

**Comment by eliotik** [comment]
@helios-ag yes you are right :-)

**Comment by helios-ag** [comment]
@eliotik Do you willing to update your PR?

**Comment by eliotik** [comment]
@helios-ag just checked with ~1.8 i cannot use it with requirement of jquery version 1.10. But if we change it to ^1.8 it is ok, so may be we will go with ^1.8?

**Comment by helios-ag** [comment]
Oh, i seee, this is because of 1.8 > 1.11, but in terms of jquery, 1.8 < 1.11,  >_<.  
Ok let's go with caret.

**Comment by eliotik** [comment]
@helios-ag updated commit, sorry, was not able to get in touch with my laptop :)

**Comment by eliotik** [comment]
@helios-ag could you please also create a new tag e.g. 1.0.1 ? i'm using helios-ag/fm-elfinder-bundle and it did not load new changes you merged.

**Comment by helios-ag** [comment]
done

**Pull request merged**
